steps:
- name: 'ubuntu'
  entrypoint: bash
  dir: bin
  args:
  - -c
  - |
    apt-get update -y
    apt-get install -y conntrack sudo curl
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io
    sudo usermod -aG docker $(whoami)
    docker version
    curl -L https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl > kubectl
    chmod 0750 kubectl
    curl -L  https://storage.googleapis.com/minikube-builds/master/minikube-linux-amd64 > minikube
    chmod 0750 minikube
- name: 'ubuntu'
  entrypoint: bash
  args:
  - -xeuc
  - |
    PATH="$${PATH}:$${PWD}/bin"
    {
      apt-get update -y
      apt-get install -y conntrack sudo iptables
      apt-get install -y docker-ce docker-ce-cli containerd.io

    } >/dev/null

    minikube start --driver=none --alsologtostderr --force 
    kubectl get pods -A

options:
  machineType: N1_HIGHCPU_8
