steps:
- name: 'ubuntu'
  entrypoint: bash
  dir: bin
  args:
  - -c
  - |
    apt-get update -y
    apt-get install -y conntrack sudo curl
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    sudo usermod -aG docker $(whoami)
    curl -L https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl > kubectl
    chmod 0750 kubectl
    curl -L  https://storage.googleapis.com/minikube-builds/master/minikube-linux-amd64 > minikube
    chmod 0750 minikube
- name: 'ubuntu'
  entrypoint: bash
  args:
  - -xeuc
  - |
    PATH="$${PATH}:$${PWD}/bin"
    {
      apt-get update -y
      apt-get install -y conntrack sudo
    } >/dev/null

    minikube start --driver=none --listen-address=0.0.0.0 --alsologtostderr --force 
    kubectl get pods -A

options:
  machineType: N1_HIGHCPU_8
