steps:
- name: 'ubuntu'
  entrypoint: bash
  dir: bin
  args:
  - -c
  - |
    apt-get update -y
    apt-get install -y conntrack sudo curl
    docker version
    curl -L https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl > kubectl
    chmod 0750 kubectl
    curl -L  https://storage.googleapis.com/minikube-builds/master/minikube-linux-amd64 > minikube
    chmod 0750 minikube
- name: 'ubuntu'
  entrypoint: bash
  args:
  - -xeuc
  - |
    PATH="$${PATH}:$${PWD}/bin"
    {
      apt-get update -y
      apt-get install -y conntrack sudo iptables
      apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      apt-get update -y
      apt install -y docker-ce docker-ce-cli containerd.io


    } >/dev/null

    minikube start --driver=none --alsologtostderr --force 
    kubectl get pods -A

options:
  machineType: N1_HIGHCPU_8
