steps:
- name: gcr.io/vic-modern-cicd-1/kind:latest
  entrypoint: 'bash'
  args:
    - -c
    - |
      kind create cluster
      kubectl cluster-info --context kind-kind
options:
  machineType: N1_HIGHCPU_8