steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - -c
    - |
      docker build -t minikube-kic .
- name: minikube-kic
  entrypoint: 'bash'
  args:
    - -c
    - |
      /usr/local/bin/entrypoint minikube start --force -v=8
options:
  machineType: N1_HIGHCPU_8
